greensmoothieproject/config/routes.rb
Greensmoothieproject::Application.routes.draw do
  resources :ailments

  resources :recipes

  root 'ailments#index'

end

greensmoothieproject/app/models/ailment.rb
class Ailment < ActiveRecord::Base
	has_many :ailment_recipes
	has_many :recipes, through: :ailment_recipes
end

greensmoothieproject/app/models/ailment_recipe.rb
class AilmentRecipe < ActiveRecord::Base
  belongs_to :ailment
  belongs_to :recipe
end

greensmoothieproject/app/models/recipe.rb
class Recipe < ActiveRecord::Base
	has_many :ailment_recipes
	has_many :ailments, through: :ailment_recipes

	#delegate :url, to: :recipe
end

greensmoothieproject/app/controllers/ailments_controller.rb
class AilmentsController < ApplicationController
  def index
  	@ailments = Ailment.all
  end

  def update
  	@ailment = Ailment.find(params[:id])
  end

end

greensmoothieproject/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

greensmoothieproject/app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  # def index
  # 	@recipes = Recipe.all
  # end

    def index
      if params[:search].size == 0
       @recipes = []
     # elsif params[:search].--- if ailment not in db?
     #  @recipes = []
     # elsif params[:search].include(:ailment)
        flash[:error] = "Please enter an ailment."
      else
        # based on name that's passed in, look up ailment, then ask for its recipes - get recipes for particular affliction
        #want to have a case-insensitive find_by for ActiveRecord -- change find by to where method
        if affliction = Ailment.where("lower(name) = ?", params[:search].downcase).first
          randomly_selected_recipe = affliction.recipes.sample
        @recipe_name = randomly_selected_recipe.name
        @recipe_url = randomly_selected_recipe.url
        @recipe_description = randomly_selected_recipe.description
        else
          flash[:error] = "Please enter an existing ailment."
        end
      end


      if params[:search].size == 0 || affliction.nil? # there's no recipes
        # flash[:error] = "Please enter an ailment."
        redirect_to '/'
      else
        respond_to do |format|
          format.html { render action: "show" }
          format.js
        end
      end
    end
  #end
end

greensmoothieproject/app/helpers/ailments_helper.rb
module AilmentsHelper
end

greensmoothieproject/app/helpers/application_helper.rb
module ApplicationHelper
end

greensmoothieproject/app/helpers/recipes_helper.rb
module RecipesHelper
end

greensmoothieproject/app/views/ailments/index.html.erb
<div class="search-form" >
<h1 class="logo">Green Smoothie Generator</h1>

<img src="http://fc06.deviantart.net/fs41/i/2009/042/9/a/Ghost_in_a_Blender_by_venkman_project.jpg" alt="Juice" width="250" height="200">




<%= form_tag recipes_path, :remote => true, :method => :get do %>
  <div class="ui-widget">
    <%#= collection_select_tag 'name', Ailment.all, :id, :name, { include_blank: "" } %>
      <%= search_field_tag :search, params[:search], id: "tags", class: "search-query", size: "50", :placeholder => "Select an ailment" %>
      <%= submit_tag "Search", :name => nil, class: "btn btn-danger btn-lg", id: "search-submit" %>
    <div>
      <%= flash[:error] %>
    </div>
  </div>
<% end %><br>
</div>

<div id="recipe-result">
</div>

greensmoothieproject/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Greensmoothie</title>
  <link rel="stylesheet" href="//railsgirls.com/assets/bootstrap.css" />
<link rel="stylesheet" href="//railsgirls.com/assets/bootstrap-theme.css" />
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <%= favicon_link_tag 'coffee_favicon.jpg' %>
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="/">Dust off your Nutribullet, people.</a>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <li class="active"><a href="http://www.grownyc.org/greenmarket/ourmarkets">Hungry?</a></li>
      </ul>
    </div>
  </div>
</nav>




<div id="background-image"></div>
<div class="container">
  <%= yield %>
</div>

</footer>
<script src="//railsgirls.com/assets/bootstrap.js"></script>
</body>
</html>



  <footer class="footer text-center">

    <p class="disclaimer"><strong>Disclaimer:</strong><br>
    Nutrition is a supplement, not a substitute, for conventional medicine.  Please consider food allergies, carb/fruit sugar content, medicine contraindications, etc. before consuming new foods.</p>

    <a href="https://twitter.com/share" class="twitter-share-button" data-url="http://green-smoothie-generator.herokuapp.com/" data-text="Get green smoothie recommendations based on ailments!" data-via="trickortechrat" data-size="large" data-hashtags="greensmoothiegenerator">Tweet</a>
<script>!function(d,s,id){var js,fjs=d.getElementsByTagName(s)[0],p=/^http:/.test(d.location)?'http':'https';if(!d.getElementById(id)){js=d.createElement(s);js.id=id;js.src=p+'://platform.twitter.com/widgets.js';fjs.parentNode.insertBefore(js,fjs);}}(document, 'script', 'twitter-wjs');</script>
<h6>Made with ♥ at Flatiron School / <a href="https://github.com/ChavaLovesFyedka"> ChavaLovesFyedka</a></h6>
  </footer>

greensmoothieproject/app/views/recipes/show.html.erb
<div class="close-out"><%= link_to "/", "/" %></div>
  <div class="result-modal">
  <p>
    <h2 class="ailment-recipe">Here is your smoothie:</h2>
    <h2><%= link_to @recipe_name.upcase, @recipe_url, :target => "blank" %></h2>
  </p>
  <%= image_tag "skinny-tropical-green-smoothie.jpg", :id => "smoothie-image" %>
  
  <h3 class="try-again-link"><%= link_to "Meh? Try again for a new recipe >>", "/" %></h3>
  </div>



<div class = "container-fluid">
<div class="row">
  <div class="col-md-4"> 

  </div>
    <div class="col-md-4">
    <center>
   <p>Ingredients: </p>
    <p><%= @recipe_name %></p><br>
    <p><%= simple_format(@recipe_description) %></p><br>
    </div>
</div>

</br>
</br>
</br>
</br>